sudo : required
dist: xenial
language: c++
compiler: gcc
os: linux
branches:
  only:
    - master
before_install:
  - sudo apt-get install cmake bison flex build-essential binutils-dev libldap2-dev libcppunit-dev libicu-dev libxslt1-dev zlib1g-dev libboost-regex-dev libssl-dev libarchive-dev python-dev libv8-dev default-jdk libapr1-dev libaprutil1-dev libiberty-dev libhiredis-dev libtbb-dev libxalan-c-dev libnuma-dev libevent-dev libatlas-base-dev libblas-dev libatlas-dev python3-dev libcurl4-openssl-dev libtool autotools-dev automake
  - pwd
  - rm -rf ~/build
  - mkdir ~/build
script:
  - cd ~/build
  - cmake  -G "Eclipse CDT4 - Unix Makefiles" -D CMAKE_BUILD_TYPE=Release -DINCLUDE_PLUGINS=0 -DTEST_PLUGINS=0 -DMAKE_DOCS=0 -DUSE_CPPUNIT=0 -DWSSQL_SERVICE=0 -DUSE_LIBMEMECACHED=0 -DECLWATCH_BUILD_STRATEGY=SKIP -DINCLUDE_SPARK=0 -DSUPPRESS_SPARK=1 -DSPARK=0 -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DUSE_LIBXSLT=ON -DXALAN_LIBRARIES=  -D CMAKE_ECLIPSE_MAKE_ARGUMENTS=-30 ~/HPCC-Platform
  - make -j 2 package
