name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Hello world
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
        id: hello
      # This step prints an output (time) from the previous step's action.
      - name: Echo the greeting's time
        run: echo 'Hello Bela ! The time was ${{ steps.hello.outputs.time }}.'
      # This step prints an output (time) from the previous step's action.
      - name: Check CMake version
        run: cmake --version
      # This step prints an output content of user home directory
      - name: Check dir
        run: ls -l ~/
      # This step prints disk size
      - name: Check disk
        run: df -h 
      # This step prints memory
      - name: Check memory
        run: free -h
      # This step prints cpu info
      - name: Check CPU
        run: sudo cat /proc/cpuinfo
      #
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: ../MyDockerfile
        with:
           who-to-greet: 'Bela the Great'
        id: hello2
